services:
  database:
    image: "postgres:latest"

    ports:
      - ${GRPC_DB_PORT}:5432

    environment:
      POSTGRES_USER: ${GRPC_DB_USERNAME}
      POSTGRES_PASSWORD: ${GRPC_DB_PASSWORD}
      POSTGRES_DB: ${GRPC_DB_NAME}

    volumes:
      - ./db-data/:/var/lib/postgresql