services:
  database:
    image: "postgres:latest"

    ports:
      - ${ZAHLUNGSSYSTEM_DB_PORT}:5432

    environment:
      POSTGRES_USER: ${ZAHLUNGSSYSTEM_DB_USERNAME}
      POSTGRES_PASSWORD: ${ZAHLUNGSSYSTEM_DB_PASSWORD}
      POSTGRES_DB: ${ZAHLUNGSSYSTEM_DB_NAME}

    volumes:
      - ./db-data/:/var/lib/postgresql