services:
  database-grpc:
    image: "postgres:latest"

    ports:
      - ${GRPC_DB_PORT}:5432

    environment:
      POSTGRES_USER: ${GRPC_DB_USERNAME}
      POSTGRES_PASSWORD: ${GRPC_DB_PASSWORD}
      POSTGRES_DB: ${GRPC_DB_NAME}

    volumes:
      - ./db-data/:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${GRPC_DB_USERNAME} -d ${GRPC_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
